{{- $comp := .Values.gitpod.components.db -}}
{{- if $comp.gcloudSqlProxy.enabled }}
kind: Secret
apiVersion: v1
metadata:
  creationTimestamp:
  labels:
    app: {{ template "gitpod.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: gcloud-sql-token
  namespace: default
data:
  credentials.json: {{ (.Files.Get $comp.gcloudSqlProxy.credentials) | b64enc }}
{{- end }}