{{- $comp := .Values.gitpod.components.server -}}
{{- if $comp.storage.keyFilePath }}
apiVersion: v1
kind: Secret
metadata:
  name: gcp-server-storage-key
  labels:
    app: {{ template "gitpod.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  "{{ base $comp.storage.keyFilePath }}": {{ $.Files.Get $comp.storage.keyFilePath | b64enc | quote }}
{{- end }}