{{- $comp := .Values.gitpod.components.wsSync -}}
{{- if (eq $comp.remoteStorage.kind "gcloud") }}
apiVersion: v1
kind: Secret
metadata:
  name: gcp-ws-sync-key
  labels:
    app: {{ template "gitpod.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  "{{ base $comp.remoteStorage.gcloud.credentialsFile }}": {{ $.Files.Get (print "secrets/" (base $comp.remoteStorage.gcloud.credentialsFile)) | b64enc | quote }}
{{- end }}