{{- if .Values.gitpod_selfhosted -}}
{{- if .Values.gitpod_selfhosted.variants -}}
{{- if .Values.gitpod_selfhosted.variants.customCerts -}}
apiVersion: v1
kind: Secret
metadata:
  name: proxy-config-certificates
  labels:
    app: {{ template "gitpod.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  annotations:
    checksum/checksd-config: {{ ($.Files.Get .Values.gitpod.certificatesSecret.path) | sha256sum }}
data:
{{ ($.Files.Glob .Values.gitpod.certificatesSecret.path).AsSecrets | nindent 2 }}
{{- end -}}
{{- end -}}
{{- end -}}